Repository mviewer/mviewer, pull requests merged in 2022-11, with the labels that each got.

#645 tri fiches infos selon la toc
  docs/doc_tech/config_app.rst
  js/info.js
Labels: enhancement

#682 #679 utiliser des variables d'environnement depuis un fichier de config
  .gitignore
  apps/.env
  docs/doc_tech/config_environmentvar.rst
  docs/index.rst
  index.html
  js/configuration.js
  js/utils.js
Labels: enhancement

#678 #677 serve mviewer with nodejs
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: enhancement

#689 Correction affichage icon theme
  js/configuration.js
Labels: bug

#696 Upgrade OpenLayers 7.1.0
  index.html
  js/mviewer.js
  lib/openlayers/6.3.1/build/ol.js
  lib/openlayers/6.3.1/build/ol.js.map
  lib/openlayers/6.3.1/css/ol.css
  lib/openlayers/6.3.1/css/ol.css.map
  lib/openlayers/7.1.0/ol.css
  lib/openlayers/7.1.0/ol.js
  lib/openlayers/7.1.0/ol.js.map
Labels: dependencies
